---

  # https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Uninstall old packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: "{{ docker_apt_gpg_key_id }}"
        state: present

    - name: Add repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes


  # https://docs.docker.com/install/linux/docker-ce/centos/
- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Uninstall old packages
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        update_cache: yes

    - name: Add repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        state: present

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: yes
  ignore_errors: yes

- name: Flush handlers
  meta: flush_handlers

- name: Add user to docker group
  user:
    name: "{{ docker_user | default(ansible_user_id) }}"
    groups: docker
    append: yes
