---
- name: Set facts
  set_fact:
    docker_os_dict: "{{ docker_os_dicts[ansible_distribution + '_' + ansible_distribution_major_version] }}"

- name: Install Docker CE
  include_tasks: install-docker.yml

- name: Prepare Python
  include_tasks: prepare-python.yml
  when: docker_sdk_version != false or docker_compose_version != false

- name: Install Docker SDK
  include_tasks: install-docker-sdk.yml
  when: docker_sdk_version != false

- name: Install Docker Compose
  include_tasks: install-docker-compose.yml
  when: docker_compose_version != false
