---

- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Install dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - libffi-dev
          - "{{ docker_os_dict.python_dev }}"
        state: present
        update_cache: yes

- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Install dependencies
      yum:
        name:
          - gcc
          - libffi-devel
          - openssl-devel
          - "{{ docker_os_dict.python_dev }}"
        state: present
        update_cache: yes
  

- name: Update pip
  pip:
    name: pip
    version: "{{ pip_version }}"
    extra_args: --upgrade
    executable: "{{ docker_os_dict.pip }}"
