---
- name: Verify
  hosts: all
  tasks:

    - name: Check docker version
      shell: docker --version
      register: test

    - name: Assert docker version
      assert:
        that: "'Docker version' in test.stdout"

    - name: Check docker-compose version
      shell: docker-compose version
      register: test

    - name: Assert docker-compose version
      assert:
        that: "'docker-compose version' in test.stdout"

    - name: Try hello-world image
      shell: docker run hello-world
      register: test

    - name: Assert hello-world is working
      assert:
        that: "'Hello from Docker!' in test.stdout"
